namespace GungeonTogether.Networking.Enums
{
    public enum PacketType : byte
    {
        None = 0,
        PlayerPosition = 1,
        ConnectionRequest = 2,
        ConnectionAccepted = 3,
        ConnectionRejected = 4,
        Disconnect = 5,
        PlayerJoin = 6,
        PlayerLeave = 7,
        RoomChange = 8,
        EnemySpawn = 9,
        EnemyState = 10,
        EnemyDeath = 11,
        WorldState = 12,
        PlayerState = 13,
        LoadingState = 14,
        Heartbeat = 15,
        RunSeed = 16,
        LayoutHash = 17,
        LevelTransition = 18,
        RoomCleared = 19,
        RoomSealState = 20,
        LootSpawn = 21,
        LootTaken = 22,
        ConsumablesState = 23,
        ConsumablesDelta = 24,
        ChestSpawn = 25,
        ChestInteract = 26,
        ChestState = 27,
        ShopItemSold = 28,
        EnemyProjectile = 29,
        EnemyDamage = 30,
        FloorCleared = 31,
        BossScriptStart = 32,
        BossScriptStop = 33,
        ClientEnteredRoom = 34,
        PlayerProjectile = 35,
        PlayerLife = 36,
        RoomObject = 37,
        GenerationDecisions = 38,
        Explosion = 39,
        EnemyHit = 40,
        Goop = 41,
        Beam = 42,
        SkyRocket = 43,
        Pedestal = 44,
    }
}
